app/Http/routes.php
        Route::get('posting', 'TransactionController@getCustomerToPosting')->name('transaction.posting.customer');
        Route::get('void', 'TransactionController@getCustomerToVoid')->name('transaction.void.customer');
        Route::get('adjustment', 'TransactionController@getCustomerToAdjust')->name('transaction.adjustment.customer');
        Route::get('testing', 'TransactionController@getCustomerToTesting')->name('transaction.testing.customer');
        Route::get('manual', 'TransactionController@getCustomerToManual')->name('transaction.manual.customer');
        Route::get('manipulate', 'TransactionController@getCustomerToManipulate');
        // Search Transaction
        Route::get('{customer_id}/posting', 'TransactionController@getTransactionToPosting')->name('transaction.posting.detail');
        Route::post('{customer_id}/posting', 'TransactionController@postTransactionToPosting')->name('transaction.posting.process');
        Route::get('{customer_id}/void', 'TransactionController@getTransactionToVoid')->name('transaction.void.detail');
        Route::post('{customer_id}/void', 'TransactionController@postTransactionVoidProcess')->name('transaction.void.process');
        Route::get('{customer_id}/adjustment', 'TransactionController@getTransactionToAdjust')->name('transaction.adjustment.detail');
        Route::get('{customer_id}/manual', 'TransactionController@getTransactionToManual')->name('transaction.manual.detail');
        Route::post('manual', 'TransactionController@postTransactionManualProcess')->name('transaction.manual.process');
        Route::get('{customer_id}/testing', 'TransactionController@getTransactionToTesting')->name('transaction.testing.detail');
        Route::get('{customer_id}/manipulate', 'TransactionController@showManipulatePointForm')->name('transaction.manipulate.detail');
        Route::post('testing', 'TransactionController@postTransactionTestProcess')->name('transaction.testing.process');
        //Process
        Route::put('adjustment', 'TransactionController@postTransactionAdjustment')->name('transaction.adjustment.process');
        Route::post('{customer}/manipulate', 'TransactionController@manipulatePoint')->name('transaction.manipulate.process');

        // Datatables
        Route::get('posting-customer/data', 'TransactionController@getPostingCustomerData')->name('transaction.posting.customer.data');
        Route::get('void-customer/data', 'TransactionController@getVoidCustomerData')->name('transaction.void.customer.data');
        Route::get('adjustment-customer/data', 'TransactionController@getAdjustmentCustomerData')->name('transaction.adjustment.customer.data');
        Route::get('manual-customer/data', 'TransactionController@getManualCustomerData')->name('transaction.manual.customer.data');
        Route::get('testing-customer/data', 'TransactionController@getTestingCustomerData')->name('transaction.testing.customer.data');
        Route::get('manipulate-customer/data', 'TransactionController@getManipulateData')->name('transaction.manipulate.customer.data');
        Route::post('adjustment-transaction/{customerId}/data', 'TransactionController@getAdjustmentTransactionData')->name('transaction.adjustment.transaction.data');

        Route::post('void-transaction/{barcode}/data', 'TransactionController@getVoidTransactionData')->name('transaction.void.transaction.data');
        Route::post('posting-master-transaction/{barcode}/data', 'TransactionController@getPostingTransactionMasterData')->name('transaction.posting.transaction.master.data');
        Route::post('posting-detail-transaction/{barcode}/data', 'TransactionController@getPostingTransactionDetailData')->name('transaction.posting.transaction.detail.data');
        Route::post('posting-transaction-posting/data', 'TransactionController@getPostingTransactionPostingData')->name('transaction.posting.transaction.posting.data');

    });
    // Mandatory section
    Route::group(['prefix' => 'mandatory'], function(){
        Route::get('general', 'MandatoryController@generalIndex')->name('mandatory.general.index');
        Route::post('general', 'MandatoryController@generalStore')->name('mandatory.general.store');
        Route::get('general/{mandatoryId}/edit', 'MandatoryController@generalEdit')->name('mandatory.general.edit');
        Route::put('general/{mandatoryId}', 'MandatoryController@generalUpdate')->name('mandatory.general.update');

        Route::post('general/data', 'MandatoryController@getGeneralData')->name('mandatory.general.data');
        Route::delete('/', 'MandatoryController@destroy')->name('mandatory.destroy');

        Route::get('property', 'MandatoryController@propertyIndex')->name('mandatory.property.index');
        Route::post('property', 'MandatoryController@propertyStore')->name('mandatory.property.store');
        Route::get('property/{mandatoryId}/edit', 'MandatoryController@propertyEdit')->name('mandatory.general.edit');
        Route::get('property/data', 'MandatoryController@getpropertyData')->name('mandatory.property.data');
        Route::put('property/{mandatoryId}', 'MandatoryController@propertyUpdate')->name('mandatory.property.update');
    });
    // Redeem point formula section
    Route::group(['prefix' => 'redeem-point-formula'], function() {
        // Tebus Murah
        Route::resource('tebus-murah', 'RedeemPointFormula\TebusMurahController', ['except' => ['show', 'destroy']]);
        Route::post('tebus-murah/destroy', 'RedeemPointFormula\TebusMurahController@destroy')->name('redeem-point-formula.tebus-murah.destroy');

        // Tebus Gratis
        Route::resource('tebus-gratis', 'RedeemPointFormula\TebusGratisController', ['except' => ['show', 'destroy']]);
        Route::post('tebus-gratis/destroy', 'RedeemPointFormula\TebusGratisController@destroy')->name('redeem-point-formula.tebus-gratis.destroy');

        // Datatables
        Route::get('tebus-murah/data', 'RedeemPointFormula\TebusMurahController@getData')->name('redeem-point-formula.tebus-murah.data');
        Route::get('tebus-gratis/data', 'RedeemPointFormula\TebusGratisController@getData')->name('redeem-point-formula.tebus-gratis.data');
    });
    // master data section
    Route::group(['prefix' => 'master'], function() {
        Route::resource('vendor', 'Master\VendorController', ['except' =>'show', 'destroy']);
        Route::post('vendor/destroy', 'Master\VendorController@destroy');
        Route::get('vendor/data', 'Master\VendorController@getData');
        Route::get('vendor/{Id}/view', 'Master\VendorController@view');

        // Master data Brand
        Route::resource('brandData', 'Master\brandController', ['except' =>'show', 'destroy']);
        Route::post('brandData/data', 'Master\brandController@getData');
        Route::get('brandData/{id}/view', 'Master\brandController@view');

        Route::resource('department', 'Master\DepartmentController', [ 'except' => 'show', 'destroy']);
        Route::post('department/destroy', 'Master\DepartmentController@destroy');
        Route::post('department/data', 'Master\DepartmentController@getData');
        Route::get('department/{id}/edit', 'Master\DepartmentController@edit');

        Route::resource('division', 'Master\DivisionController', [ 'except' => 'show', 'destroy']);
        Route::post('division/destroy', 'Master\DivisionController@destroy');
        Route::post('division/data', 'Master\DivisionController@getData');

        Route::resource('category', 'Master\CategoryController', [ 'except' => 'show', 'destroy']);
        Route::post('category/destroy', 'Master\CategoryController@destroy');
        Route::post('category/data', 'Master\CategoryController@getData');

        Route::resource('subcategory', 'Master\SubcategoryController', [ 'except' => 'show', 'destroy']);
        Route::post('subcategory/destroy', 'Master\SubcategoryController@destroy');
        Route::post('subcategory/data', 'Master\SubcategoryController@getData');

        Route::resource('segment', 'Master\SegmentController', [ 'except' => 'show', 'destroy']);
        Route::post('segment/destroy', 'Master\SegmentController@destroy');
        Route::post('segment/data', 'Master\SegmentController@getData');

        Route::resource('country', 'Master\CountryController', [ 'except' => 'show', 'destroy']);
        Route::post('country/destroy', 'Master\CountryController@destroy');
        Route::get('country/data', 'Master\CountryController@getData');

        Route::resource('province', 'Master\ProvinceController', [ 'except' => 'show', 'destroy']);
        Route::post('province/destroy', 'Master\ProvinceController@destroy');
        Route::get('province/data', 'Master\ProvinceController@getData');

        Route::resource('city', 'Master\CityController', [ 'except' => 'show', 'destroy']);
        Route::post('city/destroy', 'Master\CityController@destroy');
        Route::get('city/data', 'Master\CityController@getData');

        Route::resource('area', 'Master\AreaController', [ 'except' => 'show', 'destroy']);
        Route::post('area/destroy', 'Master\AreaController@destroy');
        Route::get('area/data', 'Master\AreaController@getData');

        Route::resource('nationality', 'Master\NationalityController', [ 'except' => 'show', 'destroy']);
        Route::post('nationality/destroy', 'Master\NationalityController@destroy');
        Route::get('nationality/data', 'Master\NationalityController@getData');

        Route::resource('card-type/exchange', 'Master\CardTypeExchangeController', [ 'except' => 'show', 'destroy']);
        Route::post('card-type/exchange/destroy', 'Master\CardTypeExchangeController@destroy');
        Route::get('card-type/exchange/data', 'Master\CardTypeExchangeController@getData');

        Route::resource('card-type', 'Master\CardTypeController', [ 'except' => 'show', 'destroy']);
        Route::post('card-type/destroy', 'Master\CardTypeController@destroy');

app/Models/Master/Bank.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;

class Bank extends Model
{
    public $timestamps = false;

    public $incrementing = false;

}

app/Models/Master/BankCardType.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;

class BankCardType extends Model
{
    public $timestamps = false;

    public $incrementing = false;

}

app/Models/Master/Brand.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;

class Brand extends Model
{
    protected $table = 'brands';
    
     protected $primaryKey = 'id';
    
    public $timestamps = false;

    public $incrementing = false;
    


    public function product() {
        return $this->hasMany('App\Models\Master\Product', 'brand_id', $this->primaryKey);
    }
    
}

app/Models/Master/CardType.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;

class CardType extends Model
{
    protected $table = 'Z_CardType';

    protected $primaryKey = 'CARD_RECID';

    public $incrementing = false;

    public $timestamps = false;

    protected $guarded = [];

    public function getCARDIMAGEAttribute($val){
        if($val !== null){
            return env('URL_CARDTYPE_UPLOADS') . $val;
        }
        return $val;
    }

    public function parent() {
        return $this->belongsTo(CardType::class, 'CARD_GROUP', 'CARD_RECID');
    }
}

app/Models/Master/Client.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;

class Client extends Model
{
    protected $table = 'Z_Client';

    protected $primaryKey = 'CLN_RECID';

    protected $guarded = [];

    public $timestamps = false;

    public $incrementing = false;

}

app/Models/Master/Company.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    protected $table = 'Z_Company';

    protected $primaryKey = 'COMP_RECID';

    protected $guarded = [];

    public $timestamps = false;

    public $incrementing = false;

    public function customer() {
        return $this->belongsTo('App\Models\Customer', 'COMP_CUST_RECID', 'CUST_RECID');
    }

    public function city() {
        return $this->belongsTo(Lookup::class, 'COMP_CITY', 'LOK_RECID');
    }

    public function area() {
        return $this->belongsTo(Lookup::class, 'COMP_AREA', 'LOK_RECID');
    }
}

app/Models/Master/Event.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    protected $table = 'Z_Event';

    protected $primaryKey = 'EVT_RECID';

    protected $guarded = [];

    protected $dates = ['EVT_FRDATE', 'EVT_TODATE'];

    public $timestamps = false;

    public $incrementing = false;

    public function getEVTIMAGE1Attribute($val){
        if($val !== null){
            return env('URL_EVENT_UPLOADS') . $val;
        }
        return $val;
    }

    public function getEVTIMAGE2Attribute($val){
        if($val !== null){
            return env('URL_EVENT_UPLOADS') . $val;
        }
        return $val;
    }

    public function getEVTIMAGE3Attribute($val){
        if($val !== null){
            return env('URL_EVENT_UPLOADS') . $val;
        }
        return $val;
    }

    public function eventCategory(){
        return $this->belongsTo(Merchandise::class, 'EVT_CATEGORY', 'MERC_RECID');
    }
}

app/Models/Master/Gift.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;

class Gift extends Model
{
    protected $table = 'Z_Gift';

    protected $primaryKey = 'GIFT_RECID';

    protected $guarded = [];

    public $timestamps = false;

    public $incrementing = false;

    protected $dates = ['GIFT_FROM', 'GIFT_TO'];

    protected $with = ['unit'];

    public function unit() {
        return $this->belongsTo(Lookup::class, 'GIFT_UNIT', 'LOK_RECID');
    }

    public function category() {
        return $this->belongsTo(Lookup::class, 'GIFT_CATEGORY', 'LOK_RECID');
    }

    public function tenants(){
        return $this->hasMany(GiftTenant::class, 'GIFT_GIFT_RECID', $this->primaryKey);
    }
}

app/Models/Master/GiftTenant.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;

class GiftTenant extends Model
{
    protected $table = 'Z_Gift_Tenant';

    protected $primaryKey = 'GIFT_CODE';

    protected $guarded = [];

    public $timestamps = false;

    public $incrementing = false;

    public function gift() {
        return $this->belongsTo(Gift::class, 'GIFT_GIFT_RECID', 'GIFT_CODE');
    }

    public function tenant() {
        return $this->belongsTo(Gift::class, 'GIFT_TENANT', 'GIFT_CODE');
    }
}

app/Models/Master/Lookup.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Lookup extends Model
{
    use SoftDeletes;

    protected $table = 'Z_Lookup';

    protected $primaryKey = 'LOK_RECID';

    protected $guarded = [];

    public $incrementing = false;

    public $timestamps = false;

    public function subCategory() {
    	return $this->hasOne(Lookup::class, 'LOK_MAPPING', 'LOK_MAPPING_PARENT')->where('LOK_CODE', 'SUBC');
    }
    public function category() {
    	return $this->hasOne(Lookup::class, 'LOK_MAPPING', 'LOK_MAPPING_PARENT')->where('LOK_CODE', 'CATG');
    }
    public function division() {
    	return $this->hasOne(Lookup::class, 'LOK_MAPPING', 'LOK_MAPPING_PARENT')->where('LOK_CODE', 'DIVI');
    }
    public function department() {
    	return $this->hasOne(Lookup::class, 'LOK_MAPPING', 'LOK_MAPPING_PARENT')->where('LOK_CODE', 'DEPT');
    }
}

app/Models/Master/Merchandise.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;

class Merchandise extends Model
{
    protected $table = 'Z_Merchandise';

    protected $primaryKey = 'MERC_RECID';

    protected $guarded = [];

    public $incrementing = false;

    public $timestamps = false;

    public function department() {
        return $this->belongsTo(Lookup::class, 'MERC_DEPARTMENT', 'LOK_RECID');
    }

    public function division() {
        return $this->belongsTo(Lookup::class, 'MERC_DIVISION', 'LOK_RECID');
    }

    public function category() {
        return $this->belongsTo(Lookup::class, 'MERC_CATEGORY', 'LOK_RECID');
    }

    public function subcategory() {
        return $this->belongsTo(Lookup::class, 'MERC_SUBCATEGORY', 'LOK_RECID');
    }

    public function segment() {
        return $this->belongsTo(Lookup::class, 'MERC_SEGMENT', 'LOK_RECID');
    }

}

app/Models/Master/PaymentMethod.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;

class PaymentMethod extends Model
{
    public $timestamps = false;

    public $incrementing = false;

}

app/Models/Master/Product.php
<?php

namespace App\Models\Master;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;

    protected $table = 'Z_Product_Item';

    protected $primaryKey = 'PRO_RECID';

    protected $guarded = [];

    //protected $with = ['supplier','vendors','brand'];

    public $incrementing = false;

    public $timestamps = false;


    public function merchandise()
    {
        return $this->belongsTo(Merchandise::class, 'PRO_MERCHANDISE', 'MERC_CODE');
    }

    public function unit()
    {
        return $this->belongsTo(Lookup::class, 'PRO_UNIT', 'LOK_RECID');
    }

    public function brand()
    {
        return $this->belongsTo(Brand::class, 'brand_id', 'id');
    }

    public function vendors()
    {
         return $this->belongsToMany(Vendor::class, 'Product_Vendor', 'PROV_PRO_RECID', 'PROV_VDR_RECID');
    }

    public function supplier()
    {
        return $this->hasOne(ProductVendor::class, 'PROV_PRO_RECID', $this->primaryKey);
    }


}

resources/views/master/area/edit.blade.php
@extends('layouts.loyalty')
@section('css')
    <link rel="stylesheet" href="{{ asset('assets/global/vendor/select2/select2.css') }}">
@endsection
@section('content')
    <!-- Panel Inline Form -->
    <div class="panel">
        <div class="panel-body">
            @if(Session::has('success'))
                <div class="alert alert-success">
                    {{ Session::get('success') }}
                </div>
            @endif
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="row row-lg">
                <div class="col-lg-12">
                    <div class="panel" style="border:1px solid #000; display: {{ isset($ciity) ? 'block' : 'none' }} ;">
                        <div class="panel-body">
                            <form method="POST" action="{{ route('master.area.update', $lookup->LOK_RECID) }}" class="form-horizontal">
                                {{ csrf_field() }}
                                {{ method_field('PUT') }}
                                <div class="form-group form-material-sm">
                                    <div class="col-sm-6">
                                        <label class="col-sm-3 control-label text-left">Area :</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="LOK_DESCRIPTION" value="{{ $lookup->LOK_DESCRIPTION }}" required>
                                        </div>
                                    </div>
                                <div class="form-group form-material-sm">
                                    <div class="col-sm-6">
                                        <label class="col-sm-3 control-label text-left">City :</label>
                                        <div class="col-sm-9">
                                            <select name="LOK_CODEMST" class="form-control input-sm select2" id="LOK_CODEMST" required>
                                                <option value=""></option>
                                                @foreach($citys as $city)
                                                @if (isset($ciity) && $ciity->LOK_CODEMST == $city->LOK_CODEMST)
                                                    <option value="{{ $city->LOK_RECID }}" selected>{{ $ciity->LOK_DESCRIPTION }}</option>
                                                @else
                                                    <option value="{{ $city->LOK_RECID }}">{{ $city->LOK_DESCRIPTION }}</option>
                                                @endif
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                    <div class="col-sm-2">
                                        <div class="col-sm-12">
                                            <input type="checkbox" name="LOK_ACTIVE" {{ $lookup->LOK_ACTIVE == 1 ? 'checked' : '' }}> Active
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="com-sm-6">
                                        <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Panel Inline Form -->
@endsection

@section('scripts')
    <script src="{{ asset('assets/global/vendor/select2/select2.min.js') }}"></script>
    <script src="{{ asset('assets/global/js/components/datatables.js') }}"></script>
    <script src="{{ asset('assets/global/vendor/datatables/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('assets/global/vendor/datatables-fixedheader/dataTables.fixedHeader.js') }}"></script>
    <script src="{{ asset('assets/global/vendor/datatables-bootstrap/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('assets/global/vendor/datatables-responsive/dataTables.responsive.js') }}"></script>
    <script src="{{ asset('assets/global/vendor/datatables-tabletools/dataTables.tableTools.js') }}"></script>

    <script type="text/javascript">
        var oTable;
        $(function () {
            $('.select2').select2({
                'placeholder' : 'Choose One',
                'allowClear' : true,
                'width' : '100%'
            });
        })
    </script>

@endsection

resources/views/master/area/index.blade.php
@extends('layouts.loyalty')
@section('css')
    <link rel="stylesheet" href="{{ asset('assets/global/vendor/select2/select2.css') }}">
@endsection
@section('content')
    <!-- Panel Inline Form -->
    <div class="panel">
        <div class="panel-body">
            @if(Session::has('success'))
                <div class="alert alert-success">
                    {{ Session::get('success') }}
                </div>
            @endif
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="row row-lg">
                <div class="col-lg-12">
                    <br/>
                    <table class="table table-hover dataTable table-striped width-full" id="d-area">
                        <thead>
                        <tr>
                            <th>Code</th>
                            <th>Area</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                    </table>

                    <div class="panel" style="border:1px solid #000;">
                        <div class="panel-body">
                            <form method="POST" action="{{ route('master.area.store') }}" class="form-horizontal">
                                {{ csrf_field() }}
                                <div class="form-group form-material-sm">
                                    <div class="col-sm-6">
                                        <label class="col-sm-3 control-label text-left">Area :</label>
                                        <div class="col-sm-9">
                                            <input type="text" class="form-control" name="LOK_DESCRIPTION" required>
                                        </div>
                                    </div>
                                    <div class="col-sm-2">
                                        <div class="col-sm-12">
                                            <input type="checkbox" name="LOK_ACTIVE" checked> Active
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group form-material-sm">
                                    <div class="col-sm-6">
                                        <label class="col-sm-3 control-label text-left">City :</label>
                                        <div class="col-sm-9">
                                            <select name="CITY" class="form-control input-sm select2" id="CITY" required>
                                                <option value=""></option>
                                                @foreach($citys as $city)
                                                    <option value="{{ $city->LOK_RECID }}" selected>{{ $city->LOK_DESCRIPTION }}</option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                </div>
                                <div class="form-group">
                                    <div class="com-sm-6">
                                        <button type="submit" class="btn btn-primary waves-effect waves-light">Submit</button>
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- End Panel Inline Form -->

    <div class="modal fade bs-modal-sm" id="delete-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <form action="{{ url('master/area/destroy') }}" method="post" role="form">
                    {!! csrf_field() !!}
                    {!! method_field('DELETE') !!}
                    <input type="hidden" name="id" id="id">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <h4 class="modal-title">Information !</h4>
                    </div>
                    <div class="modal-body">
                        Are you sure ?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Delete</button>
                    </div>
                </form>

            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

@endsection

@section('scripts')
    <script src="{{ asset('assets/global/vendor/select2/select2.min.js') }}"></script>
    <script src="{{ asset('assets/global/js/components/datatables.js') }}"></script>
    <script src="{{ asset('assets/global/vendor/datatables/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('assets/global/vendor/datatables-fixedheader/dataTables.fixedHeader.js') }}"></script>
    <script src="{{ asset('assets/global/vendor/datatables-bootstrap/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('assets/global/vendor/datatables-responsive/dataTables.responsive.js') }}"></script>
    <script src="{{ asset('assets/global/vendor/datatables-tabletools/dataTables.tableTools.js') }}"></script>

    <script type="text/javascript">
        var oTable;
        var start;
        $(function () {
            oTable = $('#d-area').DataTable({
                ajax: '{{ url('master/area/data') }}',
                columns : [
                    { data : 'LOK_MAPPING', name: 'LOK_MAPPING'},
                    { data : 'LOK_DESCRIPTION', name: 'LOK_DESCRIPTION'},
                    { data : 'LOK_ACTIVE', name: 'LOK_ACTIVE'},
                    { data: 'action', name: 'action', searchable: false, orderable: false}
                ]
            });

            $('#delete-modal').on('show.bs.modal', function(event){
                $('#id').val($(event.relatedTarget).data('id'));
                $('#name').text($(event.relatedTarget).data('name'));
            });
            $('.select2').select2({
                'placeholder' : 'Choose One',
                'allowClear' : true,
                'width' : '100%'
            });
        })
    </script>

@endsection