app/Http/routes.php
Route::get('logout', 'AuthController@logout');
Route::get('forgot-password', 'AuthController@getForgotPassword');
Route::post('forgot-password', 'AuthController@postForgotPassword')->name('forgot-password.process');
Route::get('verify/code', 'AuthController@getVerifyCode');
Route::post('verify/code', 'AuthController@postVerifyCode');
Route::get('verify/password', 'AuthController@getPasswordResetWithCode');
Route::post('verify/password', 'AuthController@postPasswordResetWithCode');

Route::group(['middleware' => 'auth'], function() {
    Route::get('profile', 'HomeController@profile')->name('profile');
    Route::put('profile', 'HomeController@updateProfile')->name('profile.update');
    // Change password section
    Route::get('change-password', 'HomeController@changePassword')->name('change-password');
    Route::post('change-password/{username}', 'HomeController@changePasswordUpdate')->name('change-password.update');
    //Expired Point
    Route::get('expired-point', 'Admin\ExpiredPointController@index')->name('expired-point.edit');
    Route::put('expired-point', 'Admin\ExpiredPointController@update')->name('expired-point.update');
    Route::post('expired-point-rollback', 'Admin\ExpiredPointController@rollback')->name('expired-point.rollback');
    Route::post('expired-point-proses', 'Admin\ExpiredPointController@prosesPE')->name('expired-point.prosesPE');

    // Instant Gift Section
    Route::resource('instant-gift', 'Admin\InstantGiftController', ['except' => 'show', 'destroy']);
    Route::post('instant-gift/destroy', 'Admin\InstantGiftController@destroy');
    Route::post('instant-gift/data', 'Admin\InstantGiftController@data');

    // Config section
    Route::group(['prefix' => 'config'], function () {
        // User
        Route::resource('user', 'Admin\UserManagementController', ['except' => 'show', 'destroy']);
        Route::post('user/destroy', 'Admin\UserManagementController@destroy');
        Route::get('user/data', 'Admin\UserManagementController@data');
        // Role
        Route::get('role/data', 'Admin\RolesManagementController@data');
        Route::resource('role', 'Admin\RolesManagementController', ['except' => 'destroy']);
        Route::delete('role/destroy', 'Admin\RolesManagementController@destroy');
        // Menu
        Route::get('menu/data', 'Admin\MenuManagementController@data');
        Route::resource('menu', 'Admin\MenuManagementController', ['except' => 'show', 'destroy']);
        Route::post('menu/destroy', 'Admin\MenuManagementController@destroy');
        //Setting
        Route::get('general-preference', 'Admin\PreferenceController@edit')->name('config.general-preference.edit');
        Route::put('general-preference/update' , 'Admin\PreferenceController@update')->name('config.general-preference.update');
        //Expired Point
        Route::get('expired-point', 'Admin\ExpiredPointController@index')->name('config.expired-point.edit');
        Route::put('expired-point', 'Admin\ExpiredPointController@update')->name('config.expired-point.update');
        // Email Template
        Route::resource('email-template', 'Admin\EmailTemplateController', ['except' => 'show', 'destroy']);
        // Sms Template
        Route::resource('sms-templete', 'Admin\SmsTemplateController', ['except' => 'show', 'destroy']);
    });
    // Pointo
    Route::group(['prefix' => 'pointo'], function () {

        // Pointo External Tenant
        Route::resource('external-tenant', 'Pointo\ExternalTenantController', ['except' => 'show', 'destroy']);
        Route::post('external-tenant/destroy', 'Pointo\ExternalTenantController@destroy')->name('pointo.external-tenant.destroy');
        Route::post('external-tenant/data', 'Pointo\ExternalTenantController@getData')->name('pointo.external-tenant.data');

        //Pointo Card Link
        Route::resource('internal-card-link', 'Pointo\InternalCardLinkController', ['except' => 'show', 'destroy']);
        Route::post('internal-card-link/destroy', 'Pointo\InternalCardLinkController@destroy')->name('pointo.internal-card-link.destroy');
        Route::post('internal-card-link/data', 'Pointo\InternalCardLinkController@getData')->name('pointo.internal-card-link.data');

        // Pointo Api Setting
        Route::get('api-setting', 'Pointo\ApiSettingController@index');
        Route::put('api-setting/update' , 'Pointo\ApiSettingController@update')->name('pointo.api-setting.update');
    });
    // customer section
    Route::group(['prefix' => 'customer'], function(){
        Route::get('/search', 'CustomerController@index')->name('customer.search');
        Route::get('/mass-delete', 'CustomerController@massDelete')->name('customer.mass-delete');
        Route::post('/process-mass-delete', 'CustomerController@processMassDelete')->name('customer.process-mass-delete');
        Route::get('/total', 'CustomerController@total')->name('customer.total');
        Route::get('/dataCustomer', 'CustomerController@getDataCustomer')->name('customer.dataCustomer');
        Route::get('/dataCustomerCard', 'CustomerController@getDataCustomercard')->name('customer.dataCustomercard');
        Route::get('/create', 'CustomerController@create')->name('customer.create');
        Route::post('/', 'CustomerController@store')->name('customer.store');

        //export data excel

        Route::get('/exportbystore', 'CustomerController@exportByStore')->name('customer.exportbystore');
        Route::get('/exportByExchange', 'CustomerController@getDataCustomercard')->name('customer.exportByExchange');
        Route::get('/exportBynewCustomer', 'CustomerController@getDataCustomer')->name('customer.exportBynewCustomer');

        Route::get('{customer_id}/edit', 'CustomerController@edit');
        Route::put('{customer_id}', 'CustomerController@update');
        Route::get('{customer_id}/detail', 'CustomerController@detail')->name('customer.detail');
        Route::get('{customer_id}/address', 'CustomerController@getAddresses');
        Route::get('{customer_id}/phone', 'CustomerController@getPhones');
        Route::get('{customer_id}/email', 'CustomerController@getEmails');
        Route::get('{customer_id}/interest', 'CustomerController@getInterests');
        Route::get('{customer_id}/exchange', 'CustomerController@customerExchange')->name('customer.detail.card-exchange');
        Route::post('{customer_id}/exchange/data', 'CustomerController@getCustomerexchange')->name('customer.detail.card-exchange.data');
        Route::get('{customer_id}/log', 'CustomerController@getCustomerLogs')->name('customer.detail.logs');
        Route::get('{customer_id}/points', 'CustomerController@getCustomerTransactionHistory')->name('customer.detail.point-history');
        Route::get('transaction/{id}/receipt', 'CustomerController@showTransactionDetailReceipt')->name('customer.detail.view-receipt');
        Route::get('transaction/{id}/receipt/{receipt_no}/product', 'CustomerController@showTransactionDetailProduct')->name('customer.detail.view-product');
        Route::get('/customerTransaction', 'CustomerController@getCustomerTransaction')->name('customer.customerTransaction');

        //Address
        Route::get('{customer_id}/address/{address_id}/edit', 'CustomerController@editAddress');
        Route::post('address', 'CustomerController@storeAddress')->name('customer.address.store');
        Route::put('address/{address_id}', 'CustomerController@updateAddress')->name('customer.address.update');
        Route::delete('address/destroy', 'CustomerController@deleteAddress')->name('customer.address.delete');
        //Phone
        Route::get('{customer_id}/phone/{phone_id}/edit', 'CustomerController@editPhone');
        Route::post('phone', 'CustomerController@storePhone')->name('customer.phone.store');
        Route::put('phone/{phone_id}', 'CustomerController@updatePhone')->name('customer.phone.update');
        Route::delete('phone/destroy', 'CustomerController@deletePhone')->name('customer.phone.delete');
        //Email
        Route::get('{customer_id}/email/{email_id}/edit', 'CustomerController@editEmail');
        Route::post('email', 'CustomerController@storeEmail')->name('customer.email.store');
        Route::put('email/{email_id}', 'CustomerController@updateEmail')->name('customer.email.update');
        Route::delete('email/destroy', 'CustomerController@deleteEmail')->name('customer.email.delete');
        //Interest
        Route::get('{customer_id}/interest/{interest_id}/edit', 'CustomerController@editInterest');
        Route::post('interest', 'CustomerController@storeInterest')->name('customer.interest.store');
        Route::put('interest/{interest_id}', 'CustomerController@updateInterest')->name('customer.interest.update');
        Route::delete('interest/destroy', 'CustomerController@deleteInterest')->name('customer.interest.delete');

        //Card Exchange
        Route::get('card-exchanges/search', 'CustomerController@getCardExchanges')->name('cardExchange.search');
        Route::get('card-exchanges', 'CustomerController@getCardExchanges');
        Route::get('card-exchange/{id}/edit', 'CustomerController@editCardExchange');
        Route::post('card-exchange/{id}', 'CustomerController@updateCardExchange')->name('customer.card-exchange.update');

        // Datatables
        Route::get('data', 'CustomerController@getData');
        Route::post('{customer_id}/address/data', 'CustomerController@getAddressData');
        Route::get('{customer_id}/phone/data', 'CustomerController@getPhoneData');
        Route::get('{customer_id}/email/data', 'CustomerController@getEmailData');
        Route::get('{customer_id}/interest/data', 'CustomerController@getInterestData');
        Route::get('{customer_id}/exchange/data', 'CustomerController@getExchangeData')->name('customer.detail.exchange.data');
        Route::post('card-exchanges/data', 'CustomerController@getCardExchangeData')->name('customer.card-exchanges.data');
        // Customer Group

app/Http/Controllers/Pointo/ApiSettingController.php
<?php
namespace App\Http\Controllers\Pointo;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Client;
use App\Models\Customer;
use App\Models\Preference;
use Illuminate\Http\Request;
use Session;


class ApiSettingController extends Controller {

	private $parent;
	private $parent_link;

	public function __construct() {
		$this->parent = 'Pointo';
		$this->parent_link = '';
	}

	public function index() {
        $breadcrumbs = 'Api Setting';
        $parent = $this->parent;
        $parent_link = $this->parent_link;

        $customers = Customer::orderBy('CUST_CODE', 'DESC')->get();
        $client = Client::where('CLN_NO', substr(Session::get('pnum'), 0, 2))->first();

        $pointo = new \stdClass;
        $pointo->url = Preference::where('key', 'pointo_api_url')->first();
        $pointo->url = (!empty($pointo->url)) ? $pointo->url->value : '';
        $pointo->username = Preference::where('key', 'pointo_api_username')->first();
        $pointo->username = (!empty($pointo->username)) ? $pointo->username->value : '';
        $pointo->password = Preference::where('key', 'pointo_api_password')->first();
        $pointo->password = (!empty($pointo->password)) ? $pointo->password->value : '';
        $pointo->token = Preference::where('key', 'pointo_api_token')->first();
        $pointo->token = (!empty($pointo->token)) ? $pointo->token->value : '';

        return view('pointo.api-setting.index', compact('breadcrumbs', 'parent', 'parent_link', 'customers', 'client', 'pointo'));
	}

	public function update(Request $request) {
        $rules = [
            'api_url' => 'required',
            'user' => 'required',
            'password' => 'required',
            'token' => 'required',
            'customer' => 'required'
        ];
        $this->validate($request, $rules);

        $pointoUrl = Preference::where('key', 'pointo_api_url')->first();
        $pointoUrl->value = $request->input('api_url');
        $pointoUrl->save();
        $pointoUsername = Preference::where('key', 'pointo_api_username')->first();
        $pointoUsername->value = $request->input('user');
        $pointoUsername->save();
        $pointoPassword = Preference::where('key', 'pointo_api_password')->first();
        $pointoPassword->value = $request->input('password');
        $pointoPassword->save();
        $pointoToken = Preference::where('key', 'pointo_api_token')->first();
        $pointoToken->value = $request->input('token');
        $pointoToken->save();

        $client = Client::where('CLN_NO', substr(Session::get('pnum'), 0, 2))->first();
        $client->CLN_APEX_CUSTOMER = $request->input('customer');
        $client->save();

        return redirect()->back()->with('success', 'Update Success');
	}
}
?>

app/Http/Controllers/Pointo/ExternalTenantController.php
<?php
namespace App\Http\Controllers\Pointo;

use App\Http\Controllers\Controller;
use App\Models\Master\Tenant;
use Faker\Provider\Uuid;
use Illuminate\Http\Request;
use Session, Datatables;

class ExternalTenantController extends Controller {

	private $parent;
	private $parent_link;

	public function __construct() {
		$this->parent = 'External Tenant List';
		$this->parent_link = route('pointo.external-tenant.index');
	}

	public function index() {

		$this->parent = 'Pointo';
        $data['breadcrumbs'] = 'External Tenant List';
        $data['parent'] = $this->parent;
        $data['parent_link'] = $this->parent_link;

         return view('pointo.external-tenant.index', $data);
	}

	public function create() {
        $data['breadcrumbs'] = 'New External Tenant';
        $data['parent'] = $this->parent;
        $data['parent_link'] = $this->parent_link;

       return view('pointo.external-tenant.form', $data);
	}

    public function store(Request $request)
    {
		$rules = [
		    'description' => 'required',
		    'card_name' => 'required',
		    'card_code' => 'required'
		];
		$this->validate($request, $rules);

        $input = $request->all();
        $clientNo = substr(Session::get('pnum'), 0, 2);

        $ExternalTenant = new Tenant;
        $ExternalTenant->TNT_RECID = Uuid::uuid();
        $ExternalTenant->TNT_PNUM = '0101';
        $ExternalTenant->TNT_PTYPE = $clientNo;
        $ExternalTenant->TNT_DESC = $input['description'];
        $ExternalTenant->TNT_TEXT = $input['card_name'];
        $ExternalTenant->TNT_UNIT = $input['card_code'];
        $ExternalTenant->TNT_ACTIVE = (isset($input['status']) && $input['status'] == 'on') ? 1 : 0 ;
        $ExternalTenant->save();

        return redirect()->route('pointo.external-tenant.index')->with('notif_success', 'Data has been saved!');
    }

    public function edit($id)
    {
	    $parent = $this->parent;
	    $parent_link = $this->parent_link;
	    $breadcrumbs = 'Update External Tenant';

	    $ExternalTenant = Tenant::findOrFail($id);

	    return view('pointo.external-tenant.form', compact('ExternalTenant', 'parent', 'parent_link', 'breadcrumbs'));
    }
   
   public function update(Request $request, $id)
   {
        $rules = [
		    'description' => 'required',
		    'card_name' => 'required',
		    'card_code' => 'required'
        ];
        $this->validate($request, $rules);

        $input = $request->all();
        $clientNo = substr(Session::get('pnum'), 0, 2);

        $ExternalTenant = Tenant::findOrFail($id);
        $ExternalTenant->TNT_DESC = $input['description'];
        $ExternalTenant->TNT_TEXT = $input['card_name'];
        $ExternalTenant->TNT_UNIT = $input['card_code'];
        $ExternalTenant->TNT_ACTIVE = (isset($input['status']) && $input['status'] == 'on') ? 1 : 0 ;
        $ExternalTenant->save();

        return redirect()->route('pointo.external-tenant.index')->with('notif_success', 'Data has been updated!');
   }

    public function destroy(Request $request)
    {
        Tenant::destroy($request->input('id'));
        
        return redirect()->route('pointo.external-tenant.index')->with('success', 'Data has been deleted!');
    }

	public function getData() {
		$clientNo = substr(Session::get('pnum'), 0, 2);
		$ExternalTenanList = Tenant::where('TNT_PNUM', '0101')->where('TNT_PTYPE', $clientNo)->get();

		return Datatables::of($ExternalTenanList)
            ->addColumn('status', function($ExternalTenanList) {
                if ($ExternalTenanList->TNT_ACTIVE == 1) {
                    return '<i class="md-check text-success"></i>';
                } else {
                    return '<i class="md-close text-danger"></i>';
                }
            })
			->addColumn('action', function($ExternalTenanList) {
				$edit = '<a href="' .route('pointo.external-tenant.edit', $ExternalTenanList->TNT_RECID). '" style="text-decoration:none"> <button type="button" class="btn btn-primary btn-xs">Edit</button></a>';
				 $delete = '<button type="button" class="btn btn-danger btn-xs" data-id="' . $ExternalTenanList->TNT_RECID . '" data-toggle="modal" data-target="#delete-modal">Delete</button>';

				 return $edit. '&nbsp;' . $delete;
			})
			->make(true);

	}

}
?>

resources/views/pointo/external-tenant/form.blade.php
@extends('layouts.loyalty')
@section('css')
    <link rel="stylesheet" href="{{ asset('assets/global/vendor/select2/select2.css') }}">
@endsection
@section('content')
    @if(Session::has('notif_success'))
        <div class="alert alert-danger">
            {{ Session::get('notif_success') }}
        </div>
    @endif
    @if(count($errors) >0)
    <div class="alert alert-danger">
        <ul>
            @foreach($errors->all() as $error)
                <li>{{ $error }}</li>
            @endforeach
        </ul>
    </div>
    @endif
    <form method="POST" action="{{ isset($ExternalTenant) ? route('pointo.external-tenant.update', $ExternalTenant->TNT_RECID) : route('pointo.external-tenant.store')}}" class="form-horizontal">
        {{ csrf_field() }}
        {{ isset($ExternalTenant) ? method_field('PUT') : ''}}
        <div class="row">
            <div class="col-md-12">
                <div class="panel">
                    <div class="panel-body">
                        <div class="col-lg-12">
                            <div class="form-group ">
                                <div class="col-sm-12">
                                    <label class="col-sm-3 control-label text-left">Description : </label>
                                    <div class="col-sm-9">
                                        <input type="text" name="description" value="{{ isset($ExternalTenant) ? $ExternalTenant->TNT_DESC : '' }}" class="form-control input-sm " required>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group ">
                                <div class="col-sm-12">
                                    <label class="col-sm-3 control-label text-left">Card Name : </label>
                                    <div class="col-sm-9">
                                        <input type="text" name="card_name" value="{{ isset($ExternalTenant) ? $ExternalTenant->TNT_TEXT : '' }}" class="form-control input-sm " required>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group ">
                                <div class="col-sm-12">
                                    <label class="col-sm-3 control-label text-left">Card Code : </label>
                                    <div class="col-sm-9">
                                        <input type="text" name="card_code" value="{{ isset($ExternalTenant) ? $ExternalTenant->TNT_UNIT : '' }}" class="form-control input-sm " required>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group ">
                                <div class="col-sm-12">
                                    <label class="col-sm-3 control-label text-left">Status : </label>
                                    <div class="col-sm-9">
                                        <input type="checkbox" name="status"{{ isset($ExternalTenant) && ($ExternalTenant->TNT_ACTIVE == 1) ? ' checked' : '' }}  data-plugin="switchery" />
                                    </div>
                                </div>
                            </div>
							<div class="form-group pull-right">
                                <div class="col-sm-12">
                                    <button type="submit" class="btn btn-primary mart20">{{ isset($ExternalTenant) ? 'Update' : 'Submit' }}</button>
                                </div>
							</div>
                        </div>
                    </div>
                </div>                
            </div>
        </div>
    </form>
@endsection

@section('scripts')
    <script src="{{ asset('assets/global/vendor/datatables/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('assets/global/vendor/datatables-bootstrap/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('assets/global/vendor/select2/select2.min.js') }}"></script>
    <script type="text/javascript">
        $('.select2').select2({
            'placeholder' : 'Choose One',
            'allowClear' : true,
            'width' : '100%'
        });
    </script>
@endsection

resources/views/pointo/external-tenant/index.blade.php
@extends('layouts.loyalty')
@section('css')
    <link rel="stylesheet" href="{{ asset('assets/global/vendor/select2/select2.css') }}">

@endsection
@section('content')
    <div class="panel">
        <div class="panel-body">
            @if(Session::has('notif_success'))
                <div class="alert alert-success">
                    {{ Session::get('notif_success') }}
                </div>
            @endif
            @if (count($errors) > 0)
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            @endif
            <div class="row row-lg">
                <div class="col-lg-12">
                <a href="{{ route('pointo.external-tenant.create') }}" class="btn btn-primary">Add New External Tenant</a>
                    <br/><br/>
                    <table class="table table-hover dataTable table-striped width-full" id="datatable-table-external-tenant">
                        <thead>
                        <tr>
                            <th>Description</th>
                            <th>Card Name</th>
                            <th>Card Code</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
    </div>

    <div class="modal fade bs-modal-sm" id="delete-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <form action="{{ route('pointo.external-tenant.destroy') }}" method="post" role="form">
                    {!! csrf_field() !!}
                    <input type="hidden" name="id" id="modal-id">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                        <h4 class="modal-title">Information !</h4>
                    </div>
                    <div class="modal-body">
                        Are you sure ?
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn default" data-dismiss="modal">Close</button>
                        <button type="submit" class="btn btn-primary">Delete</button>
                    </div>
                </form>

            </div>
            <!-- /.modal-content -->
        </div>
        <!-- /.modal-dialog -->
    </div>

@endsection
@section('scripts')
    <script src="{{ asset('assets/global/vendor/datatables/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('assets/global/vendor/datatables-bootstrap/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('assets/global/vendor/select2/select2.min.js') }}"></script>
    <script type="text/javascript">
        var oTable;
        $(function () {
            oTable = $('#datatable-table-external-tenant').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url: '{{ route('pointo.external-tenant.data') }}',
                    method: 'POST',
                    headers: {
                        'X-CSRF-TOKEN': '{{ csrf_token() }}'
                    }
                },
                columns : [
                    { data: 'TNT_DESC', name: 'TNT_DESC', searchable: false, orderable: false},
                    { data: 'TNT_TEXT', name: 'TNT_TEXT', searchable: false, orderable: false},
                    { data: 'TNT_UNIT', name: 'TNT_UNIT', searchable: false, orderable: false},
                    { data: 'status', name: 'status', searchable: false, orderable: false},
                    { data: 'action', name: 'action', searchable: false, orderable: false}
                ]
            });
        })
        
        $('#delete-modal').on('show.bs.modal', function(event){
            $('#modal-id').val($(event.relatedTarget).data('id'));
        });
    </script>
@endsection