app/Http/routes.php
<?php
Route::get('/', function () {
    return redirect('customer/search');
});


// Auth Section
Route::get('login', 'AuthController@login');
Route::post('login', 'AuthController@postLogin');
Route::get('logout', 'AuthController@logout');
Route::get('forgot-password', 'AuthController@getForgotPassword');
Route::post('forgot-password', 'AuthController@postForgotPassword')->name('forgot-password.process');
Route::get('verify/code', 'AuthController@getVerifyCode');
Route::post('verify/code', 'AuthController@postVerifyCode');
Route::get('verify/password', 'AuthController@getPasswordResetWithCode');
Route::post('verify/password', 'AuthController@postPasswordResetWithCode');

Route::group(['middleware' => 'auth'], function() {
    Route::get('profile', 'HomeController@profile')->name('profile');
    Route::put('profile', 'HomeController@updateProfile')->name('profile.update');
    // Change password section
    Route::get('change-password', 'HomeController@changePassword')->name('change-password');
    Route::post('change-password/{username}', 'HomeController@changePasswordUpdate')->name('change-password.update');
    //Expired Point
    Route::get('expired-point', 'Admin\ExpiredPointController@index')->name('expired-point.edit');
    Route::put('expired-point', 'Admin\ExpiredPointController@update')->name('expired-point.update');
    Route::post('expired-point-rollback', 'Admin\ExpiredPointController@rollback')->name('expired-point.rollback');
    Route::post('expired-point-proses', 'Admin\ExpiredPointController@prosesPE')->name('expired-point.prosesPE');

    // Instant Gift Section
    Route::resource('instant-gift', 'Admin\InstantGiftController', ['except' => 'show', 'destroy']);
    Route::post('instant-gift/destroy', 'Admin\InstantGiftController@destroy');
    Route::post('instant-gift/data', 'Admin\InstantGiftController@data');

    // Config section
    Route::group(['prefix' => 'config'], function () {
        // User
        Route::resource('user', 'Admin\UserManagementController', ['except' => 'show', 'destroy']);
        Route::post('user/destroy', 'Admin\UserManagementController@destroy');
        Route::get('user/data', 'Admin\UserManagementController@data');
        // Role
        Route::get('role/data', 'Admin\RolesManagementController@data');
        Route::resource('role', 'Admin\RolesManagementController', ['except' => 'destroy']);
        Route::delete('role/destroy', 'Admin\RolesManagementController@destroy');
        // Menu
        Route::get('menu/data', 'Admin\MenuManagementController@data');
        Route::resource('menu', 'Admin\MenuManagementController', ['except' => 'show', 'destroy']);
        Route::post('menu/destroy', 'Admin\MenuManagementController@destroy');
        //Setting
        Route::get('general-preference', 'Admin\PreferenceController@edit')->name('config.general-preference.edit');
        Route::put('general-preference/update' , 'Admin\PreferenceController@update')->name('config.general-preference.update');
        //Expired Point
        Route::get('expired-point', 'Admin\ExpiredPointController@index')->name('config.expired-point.edit');
        Route::put('expired-point', 'Admin\ExpiredPointController@update')->name('config.expired-point.update');
        // Email Template
        Route::resource('email-template', 'Admin\EmailTemplateController', ['except' => 'show', 'destroy']);
        // Sms Template
        Route::resource('sms-templete', 'Admin\SmsTemplateController', ['except' => 'show', 'destroy']);
    });
    // Pointo
    Route::group(['prefix' => 'pointo'], function () {

        // Pointo External Tenant
        Route::resource('external-tenant', 'Pointo\ExternalTenantController', ['except' => 'show', 'destroy']);
        Route::post('external-tenant/destroy', 'Pointo\ExternalTenantController@destroy')->name('pointo.external-tenant.destroy');
        Route::post('external-tenant/data', 'Pointo\ExternalTenantController@getData')->name('pointo.external-tenant.data');

        //Pointo Card Link
        Route::resource('internal-card-link', 'Pointo\InternalCardLinkController', ['except' => 'show', 'destroy']);
        Route::post('internal-card-link/destroy', 'Pointo\InternalCardLinkController@destroy')->name('pointo.internal-card-link.destroy');
        Route::post('internal-card-link/data', 'Pointo\InternalCardLinkController@getData')->name('pointo.internal-card-link.data');

        // Pointo Api Setting
        Route::get('api-setting', 'Pointo\ApiSettingController@index');
        Route::put('api-setting/update' , 'Pointo\ApiSettingController@update')->name('pointo.api-setting.update');
    });
    // customer section
    Route::group(['prefix' => 'customer'], function(){
        Route::get('/search', 'CustomerController@index')->name('customer.search');
        Route::get('/mass-delete', 'CustomerController@massDelete')->name('customer.mass-delete');
        Route::post('/process-mass-delete', 'CustomerController@processMassDelete')->name('customer.process-mass-delete');
        Route::get('/total', 'CustomerController@total')->name('customer.total');
        Route::get('/dataCustomer', 'CustomerController@getDataCustomer')->name('customer.dataCustomer');
        Route::get('/dataCustomerCard', 'CustomerController@getDataCustomercard')->name('customer.dataCustomercard');
        Route::get('/create', 'CustomerController@create')->name('customer.create');
        Route::post('/', 'CustomerController@store')->name('customer.store');

        //export data excel

        Route::get('/exportbystore', 'CustomerController@exportByStore')->name('customer.exportbystore');
        Route::get('/exportByExchange', 'CustomerController@getDataCustomercard')->name('customer.exportByExchange');
        Route::get('/exportBynewCustomer', 'CustomerController@getDataCustomer')->name('customer.exportBynewCustomer');

        Route::get('{customer_id}/edit', 'CustomerController@edit');
        Route::put('{customer_id}', 'CustomerController@update');
        Route::get('{customer_id}/detail', 'CustomerController@detail')->name('customer.detail');
        Route::get('{customer_id}/address', 'CustomerController@getAddresses');
        Route::get('{customer_id}/phone', 'CustomerController@getPhones');
        Route::get('{customer_id}/email', 'CustomerController@getEmails');
        Route::get('{customer_id}/interest', 'CustomerController@getInterests');
        Route::get('{customer_id}/exchange', 'CustomerController@customerExchange')->name('customer.detail.card-exchange');
        Route::post('{customer_id}/exchange/data', 'CustomerController@getCustomerexchange')->name('customer.detail.card-exchange.data');
        Route::get('{customer_id}/log', 'CustomerController@getCustomerLogs')->name('customer.detail.logs');
        Route::get('{customer_id}/points', 'CustomerController@getCustomerTransactionHistory')->name('customer.detail.point-history');
        Route::get('transaction/{id}/receipt', 'CustomerController@showTransactionDetailReceipt')->name('customer.detail.view-receipt');
        Route::get('transaction/{id}/receipt/{receipt_no}/product', 'CustomerController@showTransactionDetailProduct')->name('customer.detail.view-product');
        Route::get('/customerTransaction', 'CustomerController@getCustomerTransaction')->name('customer.customerTransaction');

        //Address
        Route::get('{customer_id}/address/{address_id}/edit', 'CustomerController@editAddress');
        Route::post('address', 'CustomerController@storeAddress')->name('customer.address.store');
        Route::put('address/{address_id}', 'CustomerController@updateAddress')->name('customer.address.update');
        Route::delete('address/destroy', 'CustomerController@deleteAddress')->name('customer.address.delete');
        //Phone
        Route::get('{customer_id}/phone/{phone_id}/edit', 'CustomerController@editPhone');
        Route::post('phone', 'CustomerController@storePhone')->name('customer.phone.store');
        Route::put('phone/{phone_id}', 'CustomerController@updatePhone')->name('customer.phone.update');
        Route::delete('phone/destroy', 'CustomerController@deletePhone')->name('customer.phone.delete');
        //Email
        Route::get('{customer_id}/email/{email_id}/edit', 'CustomerController@editEmail');
        Route::post('email', 'CustomerController@storeEmail')->name('customer.email.store');
        Route::put('email/{email_id}', 'CustomerController@updateEmail')->name('customer.email.update');
        Route::delete('email/destroy', 'CustomerController@deleteEmail')->name('customer.email.delete');
        //Interest
        Route::get('{customer_id}/interest/{interest_id}/edit', 'CustomerController@editInterest');
        Route::post('interest', 'CustomerController@storeInterest')->name('customer.interest.store');
        Route::put('interest/{interest_id}', 'CustomerController@updateInterest')->name('customer.interest.update');
        Route::delete('interest/destroy', 'CustomerController@deleteInterest')->name('customer.interest.delete');

        //Card Exchange
        Route::get('card-exchanges/search', 'CustomerController@getCardExchanges')->name('cardExchange.search');
        Route::get('card-exchanges', 'CustomerController@getCardExchanges');
        Route::get('card-exchange/{id}/edit', 'CustomerController@editCardExchange');
        Route::post('card-exchange/{id}', 'CustomerController@updateCardExchange')->name('customer.card-exchange.update');

        // Datatables
        Route::get('data', 'CustomerController@getData');
        Route::post('{customer_id}/address/data', 'CustomerController@getAddressData');
        Route::get('{customer_id}/phone/data', 'CustomerController@getPhoneData');
        Route::get('{customer_id}/email/data', 'CustomerController@getEmailData');
        Route::get('{customer_id}/interest/data', 'CustomerController@getInterestData');

app/Models/Customer.php
<?php

namespace App\Models;

use App\Models\Admin\Post;
use App\Models\Master\Lookup;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    protected $table = 'Customers';

    protected $primaryKey = 'CUST_RECID';

    protected $dates = ['CUST_DOB', 'CUST_JOINDATE', 'CUST_SYSTEMDATE', 'CUST_EXPIREDATE', 'CUST_EXTENDATE'];

    public $incrementing = false;

    public $timestamps = false;

    protected $guarded = [];

    public function idType() {
        return $this->hasOne(Lookup::class, 'LOK_RECID', 'CUST_IDTYPE');
    }

    public function gender() {
        return $this->hasOne(Lookup::class, 'LOK_RECID', 'CUST_GENDER');
    }

    public function exchanges() {
        return $this->hasMany('App\Models\CustomerExchange', 'EXC_CUST_RECID', 'CUST_RECID');
    }

    public function exchangesType() {
         return $this->hasOne('App\Models\CustomerExchange', 'EXC_CUST_RECID', 'CUST_RECID');
    }

    public function email() {
        return $this->hasOne('App\Models\CustomerEmail', 'EML_CUST_RECID', 'CUST_RECID');
    }

    public function primaryEmail() {
        return $this->hasOne('App\Models\CustomerEmail', 'EML_CUST_RECID', 'CUST_RECID')->where('EML_TYPE', 1);
    }

    public function logs() {
        return $this->hasMany('App\Models\CustomerLog', 'customer_id', 'CUST_RECID');
    }

    public function emails() {
        return $this->hasMany('App\Models\CustomerEmail', 'EML_CUST_RECID', 'CUST_RECID');
    }

    public function addresses() {
        return $this->hasMany('App\Models\CustomerAddr', 'ADDR_CUST_RECID', 'CUST_RECID');
    }

    public function phones() {
        return $this->hasMany('App\Models\CustomerPhone', 'PHN_CUST_RECID', 'CUST_RECID');
    }

    public function mobilePhone() {
        return $this->hasOne('App\Models\CustomerPhone', 'PHN_CUST_RECID', 'CUST_RECID')->where('PHN_TYPE', 1);
    }

    public function homePhone() {
        return $this->hasOne('App\Models\CustomerPhone', 'PHN_CUST_RECID', 'CUST_RECID')->where('PHN_TYPE', 7);
    }

    public function businessPhone() {
        return $this->hasOne('App\Models\CustomerPhone', 'PHN_CUST_RECID', 'CUST_RECID')->where('PHN_TYPE', 4);
    }

    public function companyPhone() {
        return $this->hasOne('App\Models\CustomerPhone', 'PHN_CUST_RECID', 'CUST_RECID')->where('PHN_TYPE', 10);
    }

    public function facsimilePhone() {
        return $this->hasOne('App\Models\CustomerPhone', 'PHN_CUST_RECID', 'CUST_RECID')->where('PHN_TYPE', 13);
    }

    public function children() {
        return $this->hasMany('App\Models\CustomerChild', 'CHL_CUST_RECID', 'CUST_RECID');
    }

    public function picture() {
        return $this->hasOne('App\Models\CustomerPicture', 'CUST_RECID', 'CUST_RECID');
    }

    public function interests() {
        return $this->hasMany('App\Models\CustomerInterest', 'INT_CUST_RECID', 'CUST_RECID');
    }

    public function points(){
        return $this->hasMany('App\Models\CustomerPoint', 'customer_id', 'CUST_RECID');
    }

    public function rdPoint(){
        return $this->hasOne('App\Models\CustomerPoint', 'customer_id', 'CUST_RECID')->where('code', 2);
    }

    public function addressKtp() {
        return $this->hasMany('App\Models\CustomerAddr', 'ADDR_CUST_RECID', 'CUST_RECID')->where('ADDR_TYPE', 1);
    }

    public function store()
    {
        return $this->belongsTo('App\Models\Master\Tenant', 'CUST_STORE', 'TNT_RECID');
    }

    public function addressNow() {
        return $this->hasMany('App\Models\CustomerAddr', 'ADDR_CUST_RECID', 'CUST_RECID')->where('ADDR_TYPE', 2);
    }

    public function redeemTransactions(){
        return $this->hasMany('App\Models\Admin\RedeemPost', 'customer_id', 'CUST_RECID');
    }

    public function post(){
        return $this->hasMany('App\Models\Admin\Post', 'POS_BARCODE', 'CUST_BARCODE')->orderBy('POS_POST_DATE', 'DESC');
    }

    public function getRedeemPointAttribute()
    {
        return ($this->points()->redeemPoint()->first()) ? $this->points()->redeemPoint()->first()->point : 0;
    }

    public function getLuckyDrawPointAttribute()
    {
        return ($this->points()->luckyDrawPoint()->first()) ? $this->points()->luckyDrawPoint()->first()->point : 0;
    }

    public function pointExpired() {
        return $this->belongsToMany('App\Models\Admin\PointExpired','POST_PE','PE_RECID','CUST_RECID');
    }
}

resources/views/customer/delete.blade.php
@extends('layouts.loyalty')

@section('content')
    <div class="panel">
        <div class="panel-body">
            @if(Session::has('success'))
                <div class="alert alert-success">
                    {{ Session::get('success') }}
                </div>
            @endif
            @if(Session::has('notif_error'))
                <div class="alert alert-danger">
                    {{ Session::get('notif_error') }}
                </div>
            @endif
            <h3>Delete Customer</h3>
            @if($errors->has())
                <div class="alert alert-danger">
                    @foreach ($errors->all() as $error)
                        {{ $error }}<br>
                    @endforeach
                </div>
            @endif
            <form class="form-horizontal" id="form" action="{{ route('customer.process-mass-delete') }}" method="POST" enctype="multipart/form-data">
                 {!! csrf_field() !!}
                <div class="form-group form-material-sm">
                    <div class="col-sm-12">
                        <label>Delete Customer CSV file</label>
                        <br />
                        <input type="file" name="csv_file">
                    </div>
                </div>
                <div class="form-group form-material-sm">
                    <div class="col-sm-12">
                        <button type="button" id="cancel-btn" class="btn btn-danger">Cancel</button>
                        <button type="submit" class="btn btn-primary pull-right">Submit</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

@section('scripts')

@endsection

resources/views/customer/points_history.blade.php
@extends('layouts.loyalty')

@section('css')
    <link rel="stylesheet" href="{{ asset('assets/global/vendor/bootstrap-datepicker/bootstrap-datepicker.css') }}">
    <link rel="stylesheet" href="{{ asset('assets/global/vendor/select2/select2.css') }}">

@endsection

@section('content')

    <div class="panel">
        <div class="panel-body">
            <div class="row row-lg">
                <div class="col-lg-12">
                    <div class="nav-tabs-horizontal">
                        <ul class="nav nav-tabs" data-plugin="nav-tabs" role="tablist">
                            <li role="presentation"><a href="{{ route('customer.detail', $customer->CUST_RECID) }}" >Customer Profile</a></li>
                            <li class="active" role="presentation"><a href="{{route('customer.detail.point-history', $customer->CUST_RECID)}}" aria-controls="exampleTabsTwo" role="tab">Customer Transaction</a></li>

                            <li  role="presentation"><a href="{{ route('customer.detail.logs', $customer->CUST_RECID) }}">Customer Logs</a></li>
                            <li role="presentation"><a href="{{ route('customer.detail.card-exchange', $customer->CUST_RECID) }}">Customer Card exchange</a></li>
                        </ul>
                        <div class="tab-content padding-top-20">
                            <div class="tab-pane active" id="exampleTabsFour" role="tabpanel">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="dataTables_length">
                                            <label>
                                                Show
                                                <select class="form-control limit">
                                                <option data-limit="10">10</option>
                                                <option data-limit="25">25</option>
                                                <option data-limit="50">50</option>
                                                <option data-limit="100">100</option>
                                                </select>
                                                entries
                                            </label>
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="dataTables_filter">
                                            <label>
                                                Search:
                                                <input type="search" class="form-control search">
                                                <input type="hidden" class="idcustomer" value="{{ $customerId }}">
                                            </label>
                                        </div>
                                    </div>
                                </div>
                                <div class="sk-folding-cube loading-wrapper" style="display:none;">
                                    <div class="sk-cube1 sk-cube"></div>
                                    <div class="sk-cube2 sk-cube"></div>
                                    <div class="sk-cube4 sk-cube"></div>
                                    <div class="sk-cube3 sk-cube"></div>
                                </div>
                                <table class="tablesaw table-striped  dataTable table-bordered table-hover" id="point-history">
                                    <thead>
                                    <tr>
                                        <th>Date</th>
                                        <th>Time</th>
                                        <th>Store</th>
                                        <th>Amount</th>
                                        <th>RD</th>
                                        <th>Reff</th>
                                        <th>Doc No</th>
                                        <th>Type</th>
                                        <th>Action</th>
                                    </tr>
                                    </thead>
                                    <tbody>
                                    @foreach($pointHistory as $data)
                                    	<tr class="item">
                                    		<td>{{ $data->date ?: '-'}}</td>
                                    		<td>{{ $data->time ? Carbon\Carbon::parse($data->time)->format('H:i:s') : '-'}}</td>
                                    		<td>{{ $data->store_code ?: '-'}}-{{$data->store_name ?: '-'}}</td>
                                    		<td>{{ $data->amount ?: '-'}}</td>
                                    		<td>{{ thousandSeparator($data->redeem_point) ?: '-'}}</td>
                                    		<td>{{ $data->receipt_no ?: '-'}}</td>
                                            <td>{{ $data->doc_no ?: '-'}}</td>
                                    		<td>{{ $data->type ?: '-'}}</td>
                                            <td>
                                                @if($data->type == 'Earning')
                                                <a href="{{ route('customer.detail.view-receipt', $data->id) }}" type="button" class="btn btn-success btn-xs" data-toggle="modal" data-target="#view-details">Detail</a>
                                                @endif
                                            </td>
                                    	</tr>
                                    @endforeach()
                                        <tr class="iTemplate" id="item-template">
                                            <td class="item-date"></td>
                                            <td class="item-time"></td>
                                            <td class="item-store-code"></td>
                                            <td class="item-amount"></td>
                                            <td class="item-redeem-Point"></td>
                                            <td class="item-receipt-no"></td>
                                            <td class="item-doc-no"></td>
                                            <td class="item-type"></td>
                                            <td class="item-action"><a href="" type="button" class="btn btn-success btn-xs item-detail" data-toggle="modal" data-target="#view-details">Detail</a></td>
                                        </tr>
                                    </tbody>
                                </table>
                                    <div class="row mart20">
                                        <div class="col-sm-12 text-right pagination-wrapper">
                                            <button class="btn btn-primary previous-btn pagination-btn disabled" data-page="{{ $paginator->previous_page }}">
                                                Previous
                                            </button>
                                            Page
                                            <span class="current-page" data-page="{{ $paginator->current_page }}">
                                                {{ $paginator->current_page }}
                                            </span>
                                             /
                                            <span class="total-page">{{ $paginator->total_pages }}</span>
                                            <button class="btn btn-primary next-btn pagination-btn{{ (!$paginator->next_page) ? ' disabled' : '' }}" data-page="{{ $paginator->next_page }}">
                                                Next
                                            </button>
                                        </div>
                                    </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection
    <div class="modal fade" id="view-details" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

            </div>
        </div>
    </div>
    <div class="modal fade" id="view-product-modal" tabindex="-1" role="dialog" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">

            </div>
        </div>
    </div>
@section('scripts')
    <script src="{{ asset('assets/global/vendor/select2/select2.min.js') }}"></script>
    <script src="{{ asset('assets/global/js/components/datatables.js') }}"></script>
    <script src="{{ asset('assets/global/vendor/datatables/jquery.dataTables.js') }}"></script>
    <script src="{{ asset('assets/global/vendor/datatables-fixedheader/dataTables.fixedHeader.js') }}"></script>
    <script src="{{ asset('assets/global/vendor/datatables-bootstrap/dataTables.bootstrap.js') }}"></script>
    <script src="{{ asset('assets/global/vendor/datatables-responsive/dataTables.responsive.js') }}"></script>
    <script src="{{ asset('assets/global/vendor/datatables-tabletools/dataTables.tableTools.js') }}"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('.pagination-btn').click(function() {
                $('.current-page').data('page', $(this).data('page'));
                getData();
            });
            $('.limit').change(function() {
                getData(true);
            });
            $('.search').keyup(function(e) {
                if(e.keyCode == 13) {
                getData(true);
                }
            });
            function getData(resetPage = false){
                var limit = $('.limit').find('option:selected').data('limit');
                var page = $('.current-page').data('page');
                var search = $('.search').val();
                var idcustomer = $('.idcustomer').val();
                var value = 'points';

                if (resetPage) page = 1;
                var dataUrl = '{{ route('customer.customerTransaction') }}?limit=' + limit + '&page=' + page + '&s=' + search + '&idcustomer=' + idcustomer + '&value='+value;

                if (dataUrl) {
                    $('.loading-wrapper').show().siblings('table').css('opacity', 0.5);
                    $.ajax({
                        url: dataUrl,
                        success: function(data) {
                            var template = $('#item-template');
                            var items = data.DATA;
                            $('.item').remove();
                            for ($i = 0; $i < items.length; $i++) {
                                var item = items[$i];
                                clone = template.clone().removeAttr('id').removeClass('iTemplate').addClass('item');
                                $('.item-date', clone).text(item.date ? item.date : '-');
                                $('.item-time', clone).text(item.time ? item.time : '-');
                                $('.item-store-code', clone).text(item.store_code ? item.store_code : '-' +'-'+ item.store_name ? item.store_name : '-');
                                $('.item-amount', clone).text(item.amount ? item.amount : '-');
                                $('.item-redeem-Point', clone).text(item.redeem_point ? item.redeem_point : '-');
                                $('.item-doc-no', clone).text(item.doc_no ? item.doc_no : '-');
                                $('.item-receipt-no', clone).text(item.receipt_no ? item.receipt_no : '-');
                                $('.item-type', clone).text(item.type ? item.type : '-');

                                if(item.type == 'Earning'){
                                    $('.item-detail', clone).attr('href', '{{ url('customer/transaction') }}/' + item.id + '/receipt');
                                } else {
                                    $('.item-detail', clone).remove();
                                }
                                template.before(clone);
                            }
                            $('.current-page').text(data.paginator.current_page).data('page', data.paginator.current_page);
                            $('.previous-btn').data("page", data.paginator.previous_page );
                            $('.next-btn').data("page", data.paginator.next_page);
                            $('.total-page').text(data.paginator.total_pages);
                            $('.pagination-btn').removeClass('disabled');
                            if (!data.paginator.previous_page)
                                $('.previous-btn').addClass('disabled');
                            if (!data.paginator.next_page)
                                $('.next-btn').addClass('disabled');
                        }
                    }).complete(function() {
                        $('.loading-wrapper').hide().siblings('table').css('opacity', 1);
                    });
                }
            }
            $('#view-details').on('hidden.bs.modal', function (e) {
                $(this).data('bs.modal', null);
                $(this).find('.modal-content').html("");
            });
            $('#view-product-modal').on('hidden.bs.modal', function (e) {
                $(this).data('bs.modal', null);
                $(this).find('.modal-content').html("");
            });
        });
    </script>
@endsection

resources/views/customer/points_history_product_list.blade.php
<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">Transaction Detail Receipt #{{ $receiptNo }} Products</h4>
</div>
<div class="modal-body">
    <table class="table table-bordered table-hover table-striped" cellspacing="0" id="product-datatable">
        <thead>
            <tr>
                <th>Product</th>
                <th>Qty</th>
                <th>Point</th>
                <th>Price</th>
            </tr>
        </thead>
        <tbody>
            @foreach($earnings as $earning)
                <tr>
                    <td>{{ $earning->article->PRO_DESCR }}</td>
                    <td>{{ $earning->PSD_QTY ? $earning->PSD_QTY : '-' }}</td>
                    <td>{{ $earning->PSD_POINT ? $earning->PSD_POINT : '-' }}</td>
                    <td>{{ $earning->PSD_AMOUNT ? $earning->PSD_AMOUNT : '-' }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
</div>
<script src="{{ asset('assets/global/vendor/datatables-bootstrap/dataTables.bootstrap.js') }}"></script>
<script type="text/javascript">
        var oTable;
        $(function(){
            oTable = $('#product-datatable').DataTable({
                processing: true
            });
        });
</script>